language: python

python:
  - 2.7
  - 3.3

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - pip install -q --use-mirrors numpy
  - pip install -q --use-mirrors cython
  # numexpr is an optional dependency, but it does not hurt testing it
  - pip install -q --use-mirrors numexpr
  # Hmm, need to install this only for python 2.6
  #- pip install -q --use-mirrors unittest2
  - python -V

install:
  - pip install .

script:
  - mkdir empty
  - cd empty
  - python -c"import blz; blz.print_versions()"
  - nosetests blz

